### ISSUE TITLE
When having more than 8 menu choices it will crash

### ISSUE THREAD

**Issue by chriskewl** [retrocomputacion/retrobbs#10]
I added a 9th menu and it failed catastrophically. After the error I will show the menu info.

```
admin@c64pi:~/retrobbs $ sudo python3 retrobbs.py -v4

RetroBBS v0.25 (c)2021-2022
by Pablo Roldán(durandal) and
Jorge Castillo(Pastbytes)

[*] 2023-01-18 22:23:23.103 Loaded plugin: APOD
[*] 2023-01-18 22:23:23.103 Loaded plugin: HACKADAY
[*] 2023-01-18 22:23:23.104 Loaded plugin: IRC
[*] 2023-01-18 22:23:23.104 Loaded plugin: NEWSFEED
[*] 2023-01-18 22:23:23.104 Loaded plugin: ONELINER
[*] 2023-01-18 22:23:23.126 Loaded plugin: WEATHER
[*] 2023-01-18 22:23:23.571 Loaded plugin: WEBAUDIO
[*] 2023-01-18 22:23:23.572 Loaded plugin: WIKI
[*] 2023-01-18 22:23:23.572 Loaded plugin: GRABYT
Traceback (most recent call last):
  File "/home/admin/retrobbs/retrobbs.py", line 1348, in <module>
    ConfigRead()
  File "/home/admin/retrobbs/retrobbs.py", line 262, in ConfigRead
    _bbs_menues[m] = MIter(config,tkey,_bbs_menues[m])
  File "/home/admin/retrobbs/retrobbs.py", line 209, in MIter
    mentry['entries'][s] = EIter(cfg, skey, mentry['entries'][s])
  File "/home/admin/retrobbs/retrobbs.py", line 147, in EIter
    tentry = cfg[key]['entry'+str(e+1)+'title'] #Entry Title
  File "/usr/lib/python3.9/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'entry3title'
```
I changed menues = 8 to menues = 9 and added this section.

```
[MENU9]
title = Callin' Oates
sections = 2
prompt = Your choice:

[MENU9SECTION1]
title = Hall & Oates
entries = 5

entry1title = One on One
#entry1desc  = xyz
entry1key   = A
entry1func  = PCMPLAY
entry1path  = ${PATHS:bbsfiles}one_on_one.wav

entry2title = Out of Touch
#entry2desc  = 
entry2key   = B
entry2func  = PCMPLAY
entry2path  = ${PATHS:bbsfiles}out_of_touch.wav

[MENU9SECTION2]
title =
entries = 1
entry1title = Previous Menu
entry1key = _
entry1func = BACK
```

I didn't even add this to the main menu yet, I just wanted to see if it would crash. If I change menues back to menues = 8 I have no issues.

**Comment by retrocomputacion** [comment]
You forgot to change `entries` from 5 to 2 in `[MENU9SECTION1]`

**Comment by chriskewl** [comment]
You are correct. Closing this, thanks!
