### ISSUE TITLE
ModuleNotFoundError(s) common.petscii / common.dbase

### ISSUE THREAD

**Issue by psudopixel** [retrocomputacion/retrobbs#30]
a few errors popping up with a previously working installation.

```
[~/retrobbs]$ python3 retrobbs.py                                     *[master]
Traceback (most recent call last):
  File "/home/retro/retrobbs/retrobbs.py", line 92, in <module>
    import common.petscii as P
ModuleNotFoundError: No module named 'common.petscii'
```

```
[~/retrobbs]$ python3 dbmaintenance.py                                *[master]
Traceback (most recent call last):
  File "/home/retro/retrobbs/dbmaintenance.py", line 7, in <module>
    import common.dbase as DB
ModuleNotFoundError: No module named 'common.dbase'
```

**Comment by retrocomputacion** [comment]
Did you check if those files (/common/petscii.py and /common/dbase.py) exist on your install?

**Comment by psudopixel** [comment]
yes.  they exist.

```
[~/retrobbs]$ l common/petscii*                                       *[master]
-rw-r--r-- 1 retro retro 89 Apr 12 15:15 common/petscii.py
[~/retrobbs]$ l common/dbase*                                         *[master]
-rw-r--r-- 1 retro retro 6.0K May  8 09:11 common/dbase.py
```
 a clean checkout on macOS seems to work, but a clean checkout on Debian 11.7 on rasPI OS, module pathing issues...

on macOS: 
```
~/Documents/src/retrobbs/ [master] python3 --version
Python 3.11.3
```

on Debian:
```
[~/retrobbs]$ python3 --version                                        [master]
Python 3.9.2
```

**Comment by retrocomputacion** [comment]
Please check if [41a7f5d](https://github.com/retrocomputacion/retrobbs/commit/41a7f5dd5ad73e29a4e0e923b293f8578677b045) solves the issue.
I slightly changed the way modules are imported, also added the `__init__,py` files for the `common` and `plugins` directories

**Comment by psudopixel** [comment]
yes. that corrected the imports.  it all fires up now.

**Comment by retrocomputacion** [comment]
Fantastic, thanks for the report!
