### ISSUE TITLE
Module Import Errors, this might be related to Issue #30 previously reported

### ISSUE THREAD

**Issue by psudopixel** [retrocomputacion/retrobbs#33]
`retro@zerotwo:~/retrobbs master* ± python3 retrobbs.py             *[master]

Traceback (most recent call last):
  File "/home/retro/retrobbs/retrobbs.py", line 94, in <module>
    from common.connection import Connection
  File "/home/retro/retrobbs/common/connection.py", line 15, in <module>
    from common.parser import TMLParser
  File "/home/retro/retrobbs/common/parser.py", line 11, in <module>
    from encoders import petscii as P
  File "/home/retro/retrobbs/encoders/petscii.py", line 4, in <module>
    from common.imgcvt import gfxmodes
  File "/home/retro/retrobbs/common/imgcvt/__init__.py", line 1, in <module>
    from .palette import colordelta
  File "/home/retro/retrobbs/common/imgcvt/palette.py", line 3, in <module>
    import hitherdither
ModuleNotFoundError: No module named 'hitherdither'`

> retro@zerotwo:~ % python --version
Python 3.11.2

> retro@zerotwo:~ % cat /etc/debian_version
12.1

**Comment by retrocomputacion** [comment]
Is hitherdither installed correctly?
Can you import it manually using the Python interpreter?

**Comment by psudopixel** [comment]
closing this, I rebuilt my python venv and it pulled everything in correctly.  sorry about the churn.  opencv was failing to build on the pi zero 2 I was working from.

**Comment by retrocomputacion** [comment]
No problem, glad you got it sorted out.
