### ISSUE TITLE
Exception on KeyError: 'visits'

### ISSUE THREAD

**Issue by chriskewl** [retrocomputacion/retrobbs#7]
Tried to log in twice and immediately got an error about tinydb about adding visits.

```
admin@c64pi:~/retrobbs $ sudo python3 retrobbs.py -v4 > retrobbs1.txt
[*] 2023-01-18 17:06:18.529 Loaded plugin: APOD
[*] 2023-01-18 17:06:18.529 Loaded plugin: HACKADAY
[*] 2023-01-18 17:06:18.529 Loaded plugin: IRC
[*] 2023-01-18 17:06:18.529 Loaded plugin: NEWSFEED
[*] 2023-01-18 17:06:18.530 Loaded plugin: ONELINER
[*] 2023-01-18 17:06:18.550 Loaded plugin: WEATHER
[*] 2023-01-18 17:06:18.991 Loaded plugin: WEBAUDIO
[*] 2023-01-18 17:06:18.991 Loaded plugin: WIKI
[*] 2023-01-18 17:06:18.991 Loaded plugin: GRABYT
[*] 2023-01-18 17:06:19.011 Initializing server on 0.0.0.0 port 6404
[*] 2023-01-18 17:06:19.012 Awaiting a connection
[1] 2023-01-18 17:06:44.070 Incoming connection from ('192.168.1.158', 63664)
[*] 2023-01-18 17:06:44.071 Awaiting a connection
[1] 2023-01-18 17:06:45.073 Waiting for the user to press RETURN...
[1] 2023-01-18 17:06:46.943 b'\r'
[1] 2023-01-18 17:06:47.944 ID: b'RT'
[1] 2023-01-18 17:06:47.945 Terminal: [b'RETROTERM 0.14      ']
[1] 2023-01-18 17:06:47.945 TURBO56K version: 0.6
[1] 2023-01-18 17:06:47.947 Disconnected
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/admin/retrobbs/retrobbs.py", line 1192, in BBSLoop
    bbs_instance.database.newVisit()    #Total counter
  File "/home/admin/retrobbs/common/dbase.py", line 117, in newVisit
    table.update(increment('visits'), dbQ.record == 'bbs_stats')
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 415, in update
    self._update_table(updater)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 736, in _update_table
    updater(table)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 412, in updater
    perform_update(table, doc_id)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 368, in perform_update
    fields(table[doc_id])
  File "/usr/local/lib/python3.9/dist-packages/tinydb/operations.py", line 57, in transform
    doc[field] += 1
KeyError: 'visits'
[1] 2023-01-18 17:06:48.043 Total bytes sent/received: 165/25
[*] 2023-01-18 17:06:48.043 Slot freed - Awaiting a connection
[1] 2023-01-18 17:07:01.477 Incoming connection from ('192.168.1.158', 50417)
[*] 2023-01-18 17:07:01.478 Awaiting a connection
[1] 2023-01-18 17:07:02.480 Waiting for the user to press RETURN...
[1] 2023-01-18 17:07:03.809 b'\r'
[1] 2023-01-18 17:07:04.810 ID: b'RT'
[1] 2023-01-18 17:07:04.811 Terminal: [b'RETROTERM 0.14      ']
[1] 2023-01-18 17:07:04.811 TURBO56K version: 0.6
[1] 2023-01-18 17:07:04.812 Disconnected
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/admin/retrobbs/retrobbs.py", line 1192, in BBSLoop
    bbs_instance.database.newVisit()    #Total counter
  File "/home/admin/retrobbs/common/dbase.py", line 117, in newVisit
    table.update(increment('visits'), dbQ.record == 'bbs_stats')
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 415, in update
    self._update_table(updater)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 736, in _update_table
    updater(table)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 412, in updater
    perform_update(table, doc_id)
  File "/usr/local/lib/python3.9/dist-packages/tinydb/table.py", line 368, in perform_update
    fields(table[doc_id])
  File "/usr/local/lib/python3.9/dist-packages/tinydb/operations.py", line 57, in transform
    doc[field] += 1
KeyError: 'visits'
[1] 2023-01-18 17:07:05.062 Total bytes sent/received: 165/25
[*] 2023-01-18 17:07:05.062 Slot freed - Awaiting a connection

```

**Comment by retrocomputacion** [comment]
That's weird, the code do take into account the 'visits' key not existing on the first run. And in fact this hasn't been reported by others running the BBS.

I'll try some tests with an empty database.

**Comment by retrocomputacion** [comment]
I cannot reproduce, maybe your database file got corrupted?

The database is located in `bbsfiles/db.json`

Either delete your database file and start again, or compare with the fresh one I have after creating a single user with dbmaintenance.py and then login into the BBS is as follows (I edited out the pass and salt hashes just in case):

```json
{
    "USERS": {
        "1": {
            "bday": "01/01/1970",
            "country": "",
            "downbytes": 27829,
            "fname": "pablo",
            "joindate": 1674086151.8632517,
            "lastlogin": 1674086196.5856435,
            "lname": "roldan",
            "online": 0,
            "pass": "****************************************************************",
            "salt": "****************************************************************",
            "uclass": 10,
            "uname": "durandal",
            "upbytes": 64,
            "visits": 2
        }
    },
    "_default": {
        "1": {
            "record": "bbs_stats",
            "visits": 1
        }
    }
}
```
Make sure all curly brackets are paired together, there isn't any extra trailing comma or missing/extra quote character.

**Comment by chriskewl** [comment]
Here is mine...
```
{
    "USERS": {
        "1": {
            "bday": "16/12/1978",
            "country": "USA",
            "fname": "Chris",
            "joindate": 1674082850.818042,
            "lastlogin": 1674082850.8180392,
            "lname": "Haslage",
            "online": 0,
            "pass": "****************************************************************",
            "salt": "****************************************************************",
            "uclass": 10,
            "uname": "ChrisKewl",
            "visits": 1
        }
    },
    "_default": {
        "1": {
            "record": "bbs_stats",
            "uptime": 3.5575451850891113
        }
    }
}

```
The _default has no visits listed. Not sure what else it could be.

**Comment by chriskewl** [comment]
The DB file was not writable, that's why it failed. You can disregard and close this too.
