### ISSUE TITLE
Bug: When editing user in BBS it will error out and drop carrier

### ISSUE THREAD

**Issue by chriskewl** [retrocomputacion/retrobbs#8]
I tried to change my name to "ChrisKewl" instead of "chriskewl" and it errored.

```
[*] 2023-01-18 18:47:51.243 Editing user chriskewl
[1] 2023-01-18 18:47:51.246 ReceiveKey - Waiting...
[1] 2023-01-18 18:47:51.332 ReceiveKey - Received b'A'
[1] 2023-01-18 18:47:51.333 ReceiveKey - Waiting...
[1] 2023-01-18 18:47:56.795 ReceiveKey - Received b'_'
[1] 2023-01-18 18:47:56.795 ReceiveKey - Waiting...
[1] 2023-01-18 18:47:57.674 ReceiveKey - Received b'\r'
[1] 2023-01-18 18:47:59.677 ReceiveKey - Waiting...
[1] 2023-01-18 18:47:59.677 ReceiveKey - Received b'C'
[1] 2023-01-18 18:47:59.677 ReceiveKey - Waiting...
[1] 2023-01-18 18:47:59.725 ReceiveKey - Received b'H'
[1] 2023-01-18 18:47:59.726 ReceiveKey - Waiting...
[1] 2023-01-18 18:47:59.856 ReceiveKey - Received b'R'
[1] 2023-01-18 18:47:59.857 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:01.046 ReceiveKey - Received b'I'
[1] 2023-01-18 18:48:01.047 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:01.217 ReceiveKey - Received b'S'
[1] 2023-01-18 18:48:01.217 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:01.566 ReceiveKey - Received b'K'
[1] 2023-01-18 18:48:01.566 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:01.699 ReceiveKey - Received b'E'
[1] 2023-01-18 18:48:01.699 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:01.798 ReceiveKey - Received b'W'
[1] 2023-01-18 18:48:01.798 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:01.864 ReceiveKey - Received b'L'
[1] 2023-01-18 18:48:01.864 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:02.701 ReceiveKey - Received b'\r'
[1] 2023-01-18 18:48:02.704 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:06.829 ReceiveKey - Received b'A'
[1] 2023-01-18 18:48:06.830 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:08.385 ReceiveKey - Received b'\xc3'
[1] 2023-01-18 18:48:08.385 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:08.535 ReceiveKey - Received b'H'
[1] 2023-01-18 18:48:08.535 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:08.672 ReceiveKey - Received b'R'
[1] 2023-01-18 18:48:08.673 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:08.796 ReceiveKey - Received b'I'
[1] 2023-01-18 18:48:08.797 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:08.906 ReceiveKey - Received b'S'
[1] 2023-01-18 18:48:08.906 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:09.221 ReceiveKey - Received b'\xcb'
[1] 2023-01-18 18:48:09.221 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:09.441 ReceiveKey - Received b'E'
[1] 2023-01-18 18:48:09.441 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:09.540 ReceiveKey - Received b'W'
[1] 2023-01-18 18:48:09.540 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:09.673 ReceiveKey - Received b'L'
[1] 2023-01-18 18:48:09.673 ReceiveKey - Waiting...
[1] 2023-01-18 18:48:10.092 ReceiveKey - Received b'\r'
[1] 2023-01-18 18:48:10.093 Disconnected
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/admin/retrobbs/retrobbs.py", line 1250, in BBSLoop
    res = Function(*conn.MenuDefs[data][1])
  File "/home/admin/retrobbs/retrobbs.py", line 957, in EditUser
    bbs_instance.database.updateUser(uentry.doc_id,name,None,None,None,None,None)
TypeError: updateUser() missing 1 required positional argument: 'uclass'
[1] 2023-01-18 18:48:10.122 Total bytes sent/received: 1226913/181
[*] 2023-01-18 18:48:10.127 Slot freed - Awaiting a connection
```

**Comment by retrocomputacion** [comment]
Ah that's related to the previous bug in dbmaintenance, will fix right away.

**Comment by retrocomputacion** [comment]
Updated retrobbs.py, please test

**Comment by chriskewl** [comment]
Testing now. Incidentally what SEQ file editor do you use?

**Comment by chriskewl** [comment]
Yes that username portion works now but the green checkmarks on startup are MUCH slower.

**Comment by retrocomputacion** [comment]
Petmate: https://nurpax.github.io/petmate/

**Comment by retrocomputacion** [comment]
> Yes that username portion works now but the green checkmarks on startup are MUCH slower.

I had to slowdown that sequence because the wifi modems are slower to respond than an emulated connection on VICE.
That caused Retroterm to randomly crash at that point on real hardware. It is something very hard to debug so in the meanwhile I decided to slow down the feature detection.

**Comment by chriskewl** [comment]
> Petmate: https://nurpax.github.io/petmate/

What settings do you export to? Because when I save the file it doesn't look right. Thanks!

**Comment by chriskewl** [comment]
> > Yes that username portion works now but the green checkmarks on startup are MUCH slower.
> 
> I had to slowdown that sequence because the wifi modems are slower to respond than an emulated connection on VICE. That caused Retroterm to randomly crash at that point on real hardware. It is something very hard to debug so in the meanwhile I decided to slow down the feature detection.

On a real CPU it is really slow, if you can find a difference in the middle between the old quick and the new slow it'd work far better.

**Comment by retrocomputacion** [comment]
> > Petmate: https://nurpax.github.io/petmate/
> 
> What settings do you export to? Because when I save the file it doesn't look right. Thanks!

Ah, forgot Petmate doesnt save the character to switch charset when exporting to .seq
You'll need use an hex editor to insert either $8e for upper/gfx or $0e for upper/lower charset (at the start of the file).

Im now fixing some issues with the .pet and .c displayer. Those fileformats do store the charset setting.

**Comment by chriskewl** [comment]
> > > Petmate: https://nurpax.github.io/petmate/
> > 
> > What settings do you export to? Because when I save the file it doesn't look right. Thanks!
> 
> Ah, forgot Petmate doesnt save the character to switch charset when exporting to .seq You'll need use an hex editor to insert either $8e for upper/gfx or $0e for upper/lower charset (at the start of the file).

I tweeted at the creator to hopefully add the option at the beginning of the file when exporting to SEQ:
https://twitter.com/ChrisKewlTV/status/1615933669696483328

**Comment by chriskewl** [comment]
Closing this bug as fixed though I need to remember where this is for later.
